version: '2.1'

networks:
  selenoid:
    external:
      name: selenoid

services:
  myapp:
    image: myapp
    networks:
      - selenoid
    volumes:
      - ./app/config:/config
    command: /app/myapp --config=/config/app_config.cfg
    ports:
    - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
      vk_id:
        condition: service_healthy
      selenoid:
        condition: service_started

  vk_id:
    build: mock
    networks:
      - selenoid
    ports:
      - "1122:1122"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1122/" ]
      timeout: 10s
      retries: 5

  db:
    image: percona:latest
    networks:
      - selenoid
    environment:
      MYSQL_DATABASE: technoatom
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: test_qa
      MYSQL_PASSWORD: qa_test
    ports:
      - '3306:3306'
    volumes:
      - ./app/db:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-ppass", "ping", "-h", "127.0.0.1" ]
      timeout: 5s
      retries: 15

  selenoid:
    image: aerokube/selenoid:latest-release
    networks:
      - selenoid
    volumes:
      - ./selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid", "-limit", "10" ]
    ports:
      - "4444:4444"

  selenoid-ui:
    image: aerokube/selenoid-ui
    networks:
      - selenoid
    ports:
      - "8082:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
